# Generated by Django 3.2.8 on 2021-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filearchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='file_type',
            field=models.CharField(choices=[('d', 'Directory'), ('f', 'File'), ('i', 'Ignored')], max_length=1),
        ),
    ]
