# Generated by Django 3.2.8 on 2022-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filearchive', '0002_alter_path_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
